apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker
  namespace: kafka
spec:
  selector:
    matchLabels:
      run: broker
  template:
    metadata:
      labels:
        run: broker
    spec:
      containers:
        - name: broker
          image: bitnami/kafka
          ports:
            - containerPort: 9092
              hostPort: 9092
              name: broker
          env:
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://broker-service:9092
  replicas: 1