apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: kafka
spec:
  selector:
    matchLabels:
      run: sr
  template:
    metadata:
      labels:
        run: sr
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.2.1
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry-service"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "broker-service:9092"
            - name: SCHEMA_REGISTRY_LISTENERS
              value: 'http://0.0.0.0:8081'
