apiVersion: v1
kind: Service
metadata:
  name: schema-registry-service
  namespace: kafka
spec:
  type: ClusterIP
  selector:
    run: sr
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081