apiVersion: apps/v1
kind: Deployment
metadata:
  name: schema-registry
  namespace: kafka
spec:
  selector:
    matchLabels:
      run: sr
  template:
    metadata:
      labels:
        run: sr
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.2.1
          envFrom:
            - configMapRef:
                name: scehma-registry-config
          ports:
            - containerPort: 8081
              hostPort: 8081
              protocol: TCP