apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  SCHEMA_REGISTRY_URL: http://schema-registry-service.kafka.svc.cluster.local:8081
  BROKER_URL: broker-service.kafka.svc.cluster.local:9092
